<?php

  /**
   * Summary of firj_form_alter
   * @param mixed $form
   * @param mixed $form_state
   * @param mixed $form_id
   * @return void
   */

 function firj_form_alter(&$form, $form_state, $form_id) {
   if (isset($form['field_teaser'])) {
    $form['field_teaser']['#states'] = [
      'invisible' => [
        ':input[name="field_access"]' => ['value' => 5],
      ],
    ];
  }

  if (str_contains($form_id, 'node')) {
    // Views que queremos listar para os usuários.
    $keep_items = ['destaques', 'publicacoes', 'estudos', 'estudos_inteligencia_competitiva'];

    if (isset($form['field_content']))
    foreach ($form['field_content']['widget'] as $key => &$content) {
      if (is_numeric($key)) {
        if (isset($content['subform']) && $view = &$content['subform']['field_view']) {
          if ($options = &$view['widget'][0]['target_id']['#options']) {
            $options = array_filter($options, function ($key) use ($keep_items) {
              return in_array($key, $keep_items);
            }, ARRAY_FILTER_USE_KEY);
          }
        }
      }
    }
  }
}
